"""empty message

Revision ID: 092d454abdfb
Revises: 142887952607
Create Date: 2019-03-24 20:34:16.195505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092d454abdfb'
down_revision = '142887952607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###
