"""empty message

Revision ID: 142887952607
Revises: 2418b05f754a
Create Date: 2019-03-24 11:23:38.322131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142887952607'
down_revision = '2418b05f754a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_real_name'), 'users', ['real_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_real_name'), table_name='users')
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
